### ISSUE TITLE
[~2/28]Client TODO

### ISSUE THREAD

**Issue by nisi0929** [Doer-org/google-cloud-challenge-2022#114]
## TODO
- [ ] Client/ログアウト追加
- [ ] Client/参加するタイミングで参加者更新
- [ ] Client/OGP導入
- [ ] Client/参加ボタンにdisable時間をつける
- [ ] [デザインバグ対応](https://github.com/Doer-org/google-cloud-challenge-2022/issues/53)
## 重要度高くないけどやっておきたいこと 
- [ ] Client/開発環境整える
- [ ] Client/日時選択firefox対応
- [ ] Client/React Query導入
- [ ] Client/Next.js13アップグレード
